const tabQuote = [
    'If we learn to open our hearts, anyone, including the people who drive us crazy, can be our teacher.',
    'He who hath many friends hath none.',
    'Read as you taste fruit or savor wine, or enjoy friendship, love or life.',
    'Self-trust is the first secret of success.',
    'Excellence, then, is a state concerned with choice, lying in a mean, relative to us, this being determined by reason and in the way in which the man of practical wisdom would determine it.',
    'Example has more followers than reason.',
    'Everyone thinks of changing the world, but no one thinks of changing himself.',
    'Life is a travelling to the edge of knowledge, then a leap taken.',
    'In all things of nature there is something of the marvellous.',
    'Fear makes strangers of people who would be friends',
    'Vanity can easily overtake wisdom. It usually overtakes common sense.',
    'We are wiser than we know.',
    'If you light a lamp for somebody, it will also brighten your path.',
    'No valid plans for the future can be made by those who have no capacity for living now.',
    "When you realize how perfect everything is you will tilt your head back and laugh at the sky.",
    "The friendship that can cease has never been real.",
    "However many holy words you read, however many you speak, what good will they do you if you do not act on upon them?",
    "Friendship increases in visiting friends, but in visiting them seldom.",
    "A monarchy conducted with infinite wisdom and infinite benevolence is the most perfect of all possible governments.",
    "There is some self-interest behind every friendship. There is no friendship without self-interests. This is a bitter truth.",
    "A man sees in the world what he carries in his heart.",
    "Imagination will often carry us to worlds that never were. But without it we go nowhere.",
    "Believe you can and you're halfway there.",
    "You can't choose up sides on a round world.",
    "Human salvation lies in the hands of the creatively maladjusted.",
    "Being in humaneness is good. If we select other goodness and thus are far apart from humaneness, how can we be the wise?",
    "One today is worth two tomorrows.",
    "To live a pure unselfish life, one must count nothing as ones own in the midst of abundance.",
    "Democracy never lasts long. It soon wastes, exhausts and murders itself. There was never a democracy that did not commit suicide.",
    "Start where you are. Use what you have. Do what you can.",
    "A friend to all is a friend to none.",
    "Be like the flower, turn your face to the sun.",
    "One of the most beautiful qualities of true friendship is to understand and to be understood.",
    "Wishing to be friends is quick work, but friendship is a slow ripening fruit.",
    "To wear your heart on your sleeve isn't a very good plan; you should wear it inside, where it functions best.",
    "Think like a man of action; act like a man of thought.",
    "It is only the great hearted who can be true friends. The mean and cowardly, Can never know what true friendship means.",
    "Honesty is the first chapter in the book of wisdom.",
    "Light tomorrow with today!",
    "Small opportunities are often the beginning of great enterprises.",
    "Do one thing every day that scares you.",
    "Never accept ultimatums, conventional wisdom, or absolutes.",
    "We read the world wrong and say that it deceives us.",
    "Two of man's basic needs are to love and to share. Both of these needs are satisfied in greater or lesser degree by friendship.",
    "Our lives are a sum total of the choices we have made.",
    "Pure, holy simplicity confounds all the wisdom of this world and the wisdom of the flesh.",
    "A fine quotation is a diamond on the finger of a man of wit, and a pebble in the hand of a fool.",
    "Do not follow where the path may lead. Go, instead, where there is no path and leave a trail.",
    "If you were to offer a thirsty man all wisdom, you would not please him more than if you gave him a drink.",
    "Friends... they cherish one another's hopes. They are kind to one another's dreams.",
    "Compassion and happiness are not a sign of weakness but a sign of strength.",
    "What worries you masters you.",
    "Fortune befriends the bold.",
    "People who say it cannot be done should not interrupt those who are doing it.",
    "He who has injured thee was either stronger or weaker than thee. If weaker, spare him; if stronger, spare thyself.",    
    "Face your deficiencies and acknowledge them; but do not let them master you. Let them teach you patience, sweetness, insight.",        
    "Light tomorrow with today!",
    "Happiness is when what you think, what you say, and what you do are in harmony.",
    "We shall never know all the good that a simple smile can do.",
    "When in doubt, tell the truth.",
    "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.",
    "The best way to pay for a lovely moment is to enjoy it.",
    "A successful person is one who can lay a firm foundation with the bricks that others throw at him or her.",
    "It has long been an axiom of mine that the little things are infinitely the most important.",
    "Where is the Life we have lost in living? Where is the wisdom we have lost in knowledge? Where is the knowledge we have lost in information?",
    "Time stays long enough for anyone who will use it.",
    "Love is flower like; Friendship is like a sheltering tree.",
    "Those who cannot learn from history are doomed to repeat it.",
    "Blow, blow, thou winter wind Thou art not so unkind, As man's ingratitude.",
    "Ideals are an imaginative understanding of that which is desirable in that which is possible.",
    "Assume a virtue, if you have it not.",
    "The ladder of success is never crowded at the top.",
    "If I am not for myself, who will be for me? If I am not for others, what am I? And if not now, when?",
    "All I required to be happy was friendship and people I could admire.",
    "How can I believe in God when just last week I got my tongue caught in the roller of an electric typewriter?",
    "Experience is not what happens to a man. It is what a man does with what happens to him.",
    "Ability is what you're capable of doing. Motivation determines what you do.Attitude determines how well you do it.",
    "Everything has beauty, but not everyone sees it.",
    "All is flux; nothing stays still.",
    "There are only two mistakes one can make along the road to truth; not going all the way, and not starting.",
    "Until you value yourself, you won't value your time. Until you value your time, you won't do anything with it.",
    "Love is flower like; Friendship is like a sheltering tree.",
    "Rare as is true love, true friendship is rarer.",
    "The human spirit must prevail over technology.",
    "Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.",
    "The function of wisdom is to discriminate between good and evil.",
    "The higher we are placed, the more humbly we should walk.",
    "A good decision is based on knowledge and not on numbers.",
    "Let there be no purpose in friendship save the deepening of the spirit.",
    "One's friends are that part of the human race with which one can be human.",
    "One machine can do the work of fifty ordinary men. No machine can do the work of one extraordinary man.",
    "Im not in this world to live up to your expectations and you're not in this world to live up to mine.",
    "Kind words do not cost much. Yet they accomplish much.",
    "Value your friendship. Value your relationships.",
    "It is the neglect of timely repair that makes rebuilding necessary.",
    "Love is a friendship set to music.",
    "If you surrender to the wind, you can ride it.",
    "If opportunity doesn't knock, build a door.",
    "Friendship increases in visiting friends, but in visiting them seldom.",
    "No act of kindness, no matter how small, is ever wasted.",
    "We come to love not by finding a perfect person, but by learning to see an imperfect person perfectly.",
    "If you surrender to the wind, you can ride it.",
    "Trust yourself. You know more than you think you do.",
    "Bad things are not the worst things that can happen to us. Nothing is the worst thing that can happen to us!",
    "True knowledge exists in knowing that you know nothing.",
    "Friendship brings in a lot of honesty and trust into any relationship, especially a marriage.",
    "If only God would give me some clear sign! Like making a large deposit in my name in a Swiss bank.",
    "Whoso loves, believes the impossible.",
    "Rejoicing in our joy, not suffering over our suffering, makes someone a friend.",
    "True friends stab you in the front.",
    "It is not so much our friends' help that helps us, as the confidence of their help.",
    "Freedom is the right to live as we wish.",
    "How can I believe in God when just last week I got my tongue caught in the roller of an electric typewriter?",
    "Friendship is an arrangement by which we undertake to exchange small favors for big ones.",
    "I know not age, nor weariness nor defeat.",
    "Step with care and great tact, and remember that Life's a Great Balancing Act.",
    "There is only one happiness in life, to love and be loved.",
    "It has never been my object to record my dreams, just to realize them.",
    "Technology… the knack of so arranging the world that we don’t have to experience it.",
    "Quality is not an act, it is a habit.",
    "In three words I can sum up everything Ive learned about life: it goes on.",
    "To follow, without halt, one aim: There is the secret of success.",
    "Try not to become a man of success, but rather try to become a man of value.",
    "Love has no age, no limit; and no death.",
    "Learn from yesterday, live for today, hope for tomorrow.",
    "Time is the most valuable thing a man can spend.",
    "The important thing is this: to be able at any moment to sacrifice what we are for what we could become.",
    "If you're walking down the right path and you're willing to keep walking, eventually you'll make progress.",
    "We all live with the objective of being happy; our lives are all different and yet the same.",
    "The only true wisdom is in knowing you know nothing.",
    "If only wed stop trying to be happy wed have a pretty good time.",
    "Speak when you are angry and you will make the best speech you will ever regret.",
    "Courage is going from failure to failure without losing enthusiasm.",
    "Learn from yesterday, live for today, hope for tomorrow.",
    "If you love someone, set them free. If they come back they're yours; if they don't they never were.",
    "Be what you are. This is the first step toward becoming better than you are.",
    "Happiness depends upon ourselves.",
    "You need chaos in your soul to give birth to a dancing star.",
    "We are wiser than we know.",
    "A friend is someone who gives you total freedom to be yourself.",
    "There are no strangers here; Only friends you haven't yet met.",
    "You can't separate peace from freedom because no one can be at peace unless he has his freedom.",
    "The man who trusts men will make fewer mistakes than he who distrusts them.",
    "Love is the only force capable of transforming an enemy into a friend.",
    "Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.",
    "Compassion and happiness are not a sign of weakness but a sign of strength.",
    "Love is the attempt to form a friendship inspired by beauty.",
    "To be happy is to be able to become aware of oneself without fright.",
    "Good people are good because they've come to wisdom through failure. We get very little wisdom from success, you know.",
    "A friend in power is a friend lost.",
    "The trouble with most people is that they think with their hopes or fears or wishes rather than with their minds.",
    "Life is divided into the horrible and the miserable.",
    "Treat people as if they were what they ought to be and you help them to become what they are capable of being.",
    "These days people seek knowledge, not wisdom. Knowledge is of the past, wisdom is of the future.",
    "Watch the little things; a small leak will sink a great ship.",
    "Science is organized knowledge. Wisdom is organized life.",
    "To bring anything into your life, imagine that it's already there.",
    "Honesty is the best policy.",
    "When you doubt your power, you give power to your doubt.",
    "The winner ain't the one with the fastest car it's the one who refuses to lose.",
    "Life is not a problem to be solved, but a reality to be experienced.",
    "Silence at the proper season is wisdom, and better than any speech.",
    "Happiness does not come about only due to external circumstances; it mainly derives from inner attitudes.",
    "In the end, we will remember not the words of our enemies, but the silence of our friends.",
    "A quarrel between friends, when made up, adds a new tie to friendship.",
    "The way we communicate with others and with ourselves ultimately determines the quality of our lives.",
    "When people are like each other they tend to like each other.",
    "By accepting yourself and being fully what you are, your presence can make others happy.",
    "No man is free who is not master of himself.",
    "He who knows, does not speak. He who speaks, does not know.",
    "You must welcome change as the rule but not as your ruler.",
    "See the positive side, the potential, and make an effort.",
    "The only person who never makes mistakes is the person who never does anything.",
    "Love is the master key that opens the gates of happiness.",
    "Think like a man of action; act like a man of thought.",
    "We must learn to live together as brothers or perish together as fools.",
    "There are two ways of spreading light: to be the candle or the mirror that reflects it.",
    "The time to repair the roof is when the sun is shining.",
    "Friendship with ones self is all important, because without it one cannot be friends with anyone else in the world.",
    "Love and compassion open our own inner life, reducing stress, distrust and loneliness.",
    "Friendship is an arrangement by which we undertake to exchange small favors for big ones.",
    "Friendship, like love, is destroyed by long absence, though it may be increased by short intermissions.",
    "You have to take it as it happens, but you should try to make it happen the way you want to take it.",
    "Silence is a true friend who never betrays.",
    "All difficult things have their origin in that which is easy, and great things in that which is small.",
    "Talk doesn't cook rice.",
    "A Constitution of Government once changed from Freedom, can never be restored. Liberty, once lost, is lost forever.",
    "The most technologically efficient machine that man has ever invented is the book.",
    "Happiness can exist only in acceptance.",
    "There are no strangers here; Only friends you haven't yet met.",
    "Set your goals high, and don't stop till you get there.",
    "Rare as is true love, true friendship is rarer.",
    "I destroy my enemies when I make them my friends.",
    "Speak when you are angry and you will make the best speech you will ever regret.",
    "Technology presumes there’s just one right way to do things and there never is.",
    "Friendship is certainly the finest balm for the pangs of disappointed love.",
    "We respect our elders. There is wisdom that comes from experience, and I am not going to stop learning from wise counsel.",
    "Eternal nothingness is fine if you happen to be dressed for it.",
    "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    "It is easier to live through someone else than to become complete yourself.",
]

export default tabQuote